name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install this package
        run: pip install -e '.[dev]'

      - name: Run tests and generate coverage reports
        if: runner.os != 'Windows'
        run: pytest --cov lifegraph --cov-report=xml --cov-report=term

      - name: Run tests (Windows, skip examples)
        if: runner.os == 'Windows'
        run: pytest --cov lifegraph --cov-report=xml --cov-report=term tests/

      - name: Upload coverage data file
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: .coverage

  codecov-upload:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
          path: coverage-files
      - name: Combine coverage reports
        run: |
          pip install coverage
          coverage combine coverage-files
          coverage xml -o merged-coverage.xml
      - name: Upload merged coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: merged-coverage.xml
